GET http://127.0.0.1:8000/api/producto?page=1&limit=4&q=
Accept: application/json
Authorization: Bearer 14|vJ0hvphzopfymyPnYVe9sIy33HLiAyvdi9K3hPILea784f27

### guardar

POST http://127.0.0.1:8000/api/producto
Accept: application/json
Content-Type: application/json
Authorization: Bearer 14|vJ0hvphzopfymyPnYVe9sIy33HLiAyvdi9K3hPILea784f27

{
    "cod_producto": "PROD_003",
    "nombre": "SSD",
    "precio": "559.98",
    "stock": 50,
    "descripcion": "Marca Kingthon...",
    "estado": true,
    "categoria_id": 1
}