version: "3"
services:
  #PHP Service
  laravel:
    build:
      context: ./
      dockerfile: laravel.dockerfile
    image: laravel
    user: "1000:1000"
    container_name: laravel
    restart: unless-stopped
    tty: true
    #env_file:
    #  - .env
    #environment:
    #  DB_CONNECTION: mysql
    #  DB_HOST: localhost
    #  DB_PORT: 3306
    #  DB_DATABASE: laravel_test
    #  DB_USERNAME: root1
    #  DB_PASSWORD: root1
    # depends_on:
    #   - mysql
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    # networks:
    #   - app-network

  vue:
    stdin_open: true
    container_name: vue
    restart: always
    build:
      context: ../frontend_proyecto_laravue
      dockerfile: vue.dockerfile
    volumes:
      - /app/node_modules
      - ../frontend_proyecto_laravue:/app:cached
    # networks:
    #   - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose: 
      - "80"
    ports: 
      - "5173:5173"
      - "3000:3000"

  #Nginx Service
  webserver:
    depends_on:
      - laravel
      - vue
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    # networks:
    #   - app-network
  
  #Mysql DB
  db:
    image: mysql:8.1
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1
    volumes:
      - ../mysql:/mysql
    # networks:
    #   - app-network

#Docker Networks
# networks:
#   app-network:
#     driver: bridge

volumes:
  mysql:
    driver: local